#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
sudo sed -i "$ a\ \nlisten holbie3908\n \
\tbind *:80\n\tmode http\n\tbalance roundrobin\n \
\tserver 3908-web-01 34.227.91.191 check\n \
\tserver 3908-web-02 100.25.167.124 check" /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
